### ISSUE TITLE
Module breaks SOAP API

### ISSUE THREAD

**Issue by xpedicion** [netresearch/dhl-module-shipping-m2#17] opened 2018-01-06 13:57 UTC
PHP Version 7.0.19
Magento Version 2.1.10
Module Version 0.6.0

After installing the module and going to http://192.168.13.31/magento2/soap?wsdl&services=searchV1 on my dev machine I get the following (I added some linebreaks for readability):
```
<env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope" xmlns:m="http%3A%2F%2F192.168.13.31%2Fmagento2%2Fsoap%2Fdefault%3Fservices%3DsearchV1%26wsdl%3D1">
    <env:Body>
        <env:Fault>
            <env:Code>
                <env:Value>env:Receiver</env:Value>
            </env:Code>
            <env:Reason>
                <env:Text xml:lang="de">
                    Invalid parameter type "\Dhl\Shipping\Model\ShippingInfo\CheckoutInfoInterface".
                </env:Text>
            </env:Reason>
            <env:Detail>
                <m:GenericFault>
                    <m:Trace>
                        <![CDATA[
                        #0 /var/www/html/magento2/vendor/magento/framework/Reflection/TypeProcessor.php(160): Magento\Framework\Reflection\TypeProcessor->translateTypeName('\\Dhl\\Shipping\\M...') 
                        #1 /var/www/html/magento2/vendor/magento/framework/Reflection/TypeProcessor.php(229): Magento\Framework\Reflection\TypeProcessor->register('\\Dhl\\Shipping\\M...') 
                        #2 /var/www/html/magento2/vendor/magento/framework/Reflection/TypeProcessor.php(198): Magento\Framework\Reflection\TypeProcessor->_processMethod(Object(Zend\Code\Reflection\MethodReflection), 'QuoteDataAddres...') 
                        #3 /var/www/html/magento2/vendor/magento/framework/Reflection/TypeProcessor.php(162): Magento\Framework\Reflection\TypeProcessor->_processComplexType('\\Magento\\Quote\\...') 
                        #4 /var/www/html/magento2/vendor/magento/framework/Reflection/TypeProcessor.php(229): Magento\Framework\Reflection\TypeProcessor->register('\\Magento\\Quote\\...') 
                        #5 /var/www/html/magento2/vendor/magento/framework/Reflection/TypeProcessor.php(198): Magento\Framework\Reflection\TypeProcessor->_processMethod(Object(Zend\Code\Reflection\MethodReflection), 'QuoteDataAddres...') 
                        #6 /var/www/html/magento2/vendor/magento/framework/Reflection/TypeProcessor.php(162): Magento\Framework\Reflection\TypeProcessor->_processComplexType('\\Magento\\Quote\\...') 
                        #7 /var/www/html/magento2/vendor/magento/framework/Reflection/TypeProcessor.php(229): Magento\Framework\Reflection\TypeProcessor->register('\\Magento\\Quote\\...') 
                        #8 /var/www/html/magento2/vendor/magento/framework/Reflection/TypeProcessor.php(198): Magento\Framework\Reflection\TypeProcessor->_processMethod(Object(Zend\Code\Reflection\MethodReflection), 'QuoteDataCartIn...') 
                        #9 /var/www/html/magento2/vendor/magento/framework/Reflection/TypeProcessor.php(162): Magento\Framework\Reflection\TypeProcessor->_processComplexType('\\Magento\\Quote\\...') 
                        #10 /var/www/html/magento2/vendor/magento/module-webapi/Model/Config/ClassReflector.php(103): Magento\Framework\Reflection\TypeProcessor->register('\\Magento\\Quote\\...') 
                        #11 /var/www/html/magento2/vendor/magento/module-webapi/Model/Config/ClassReflector.php(72): Magento\Webapi\Model\Config\ClassReflector->extractMethodData(Object(Zend\Code\Reflection\MethodReflection)) 
                        #12 /var/www/html/magento2/vendor/magento/module-webapi/Model/ServiceMetadata.php(119): Magento\Webapi\Model\Config\ClassReflector->reflectClassMethods('Magento\\Quote\\A...', Array) 
                        #13 /var/www/html/magento2/vendor/magento/module-webapi/Model/ServiceMetadata.php(148): Magento\Webapi\Model\ServiceMetadata->initServicesMetadata() 
                        #14 /var/www/html/magento2/vendor/magento/module-webapi/Model/ServiceMetadata.php(165): Magento\Webapi\Model\ServiceMetadata->getServicesConfig() 
                        #15 /var/www/html/magento2/vendor/magento/module-webapi/Model/Soap/Wsdl/Generator.php(366): Magento\Webapi\Model\ServiceMetadata->getServiceMetadata('customerV1') 
                        #16 /var/www/html/magento2/vendor/magento/module-webapi/Model/AbstractSchemaGenerator.php(160): Magento\Webapi\Model\Soap\Wsdl\Generator->getServiceMetadata('customerV1') 
                        #17 /var/www/html/magento2/vendor/magento/module-webapi/Model/Soap/Wsdl/Generator.php(374): Magento\Webapi\Model\AbstractSchemaGenerator->getAllowedServicesMetadata(Array) 
                        #18 /var/www/html/magento2/vendor/magento/module-webapi/Model/AbstractSchemaGenerator.php(95): Magento\Webapi\Model\Soap\Wsdl\Generator->getAllowedServicesMetadata(Array) 
                        #19 /var/www/html/magento2/vendor/magento/module-webapi/Controller/Soap.php(131): Magento\Webapi\Model\AbstractSchemaGenerator->generate(Array, 'http', '192.168.13.31', 'http://192.168....') 
                        #20 /var/www/html/magento2/var/generation/Magento/Webapi/Controller/Soap/Interceptor.php(24): Magento\Webapi\Controller\Soap->dispatch(Object(Magento\Framework\App\Request\Http)) 
                        #21 /var/www/html/magento2/vendor/magento/framework/App/Http.php(135): Magento\Webapi\Controller\Soap\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http)) 
                        #22 /var/www/html/magento2/vendor/magento/framework/App/Bootstrap.php(258): Magento\Framework\App\Http->launch() 
                        #23 /var/www/html/magento2/index.php(39): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http)) 
                        #24 {main}
                        ]]>
                    </m:Trace>
                </m:GenericFault>
            </env:Detail>
        </env:Fault>
    </env:Body>
</env:Envelope>
```

**Comment by ngolatka** [comment] 2018-01-08 12:21
Hello @xpedicion 
I was able to duplicate the problem in the environment you described (Mage 2.1.10 + DHL 0.6.0).
Will give feedback as soon as there are any news.

**Comment by ngolatka** [comment] 2018-01-10 08:35
The problem will be fixed in the next version.
Sorry, but there's no ETA yet when that will be.

**Comment by mam08ixo** [comment] 2018-01-12 14:53
Thanks for the report @xpedicion. The issue is no longer present in [DHL Shipping 0.8.0](https://github.com/netresearch/dhl-module-shipping-m2/releases/tag/0.8.0).

**Closed as completed by mam08ixo** 2018-01-12 14:53 UTC
Labels: bug
